---
-
  hosts: ubu
  user: ansible
  become: true
  gather_facts: false
  tasks:
    - name: "Update Repository cache"
      apt:
       update_cache: true
       cache_valid_time: 3600
       force_apt_get: true
    - name: Install apache
      ansible.builtin.apt:
        name: apache2
        state: present
