---
-
  hosts: dev
  user: ansible
  become: true
  gather_facts: true
  tasks:
   - name: Create a directory if it does not exist
     file:
        dest: "/home/{{ item.0 }}/{{ item.1 }}"
        owner: ansible
        group: ansible
        state: directory
     with_nested:
        - [ ravi, varu  ]
        - [ photos, movies, documents ]
