---
-
  hosts: dev
  user: ansible
  become: true
  tasks:
   - name: Run a script
     script: random.sh
     register: result
     retries: 100
     until: result.stdout.find("10") != -1
     delay: 1
